### ISSUE TITLE
onItemChanged filtering

### ISSUE THREAD

**Issue by lukashass** [geprog/use-feathers#51]
Looking at:

https://github.com/geprog/use-feathers/blob/c3f8a7dc2e3e33b5f21ef72754a47ed61ecb40c0/src/useFind.ts#L32-L33

and the corresponding test:

https://github.com/geprog/use-feathers/blob/c3f8a7dc2e3e33b5f21ef72754a47ed61ecb40c0/test/useFind.test.ts#L380

This seems like a case that can not happen. When the query changes `find` is called and overrides `data.value` completely.

I stumbled across this because the test title mentions "when query is not matching anymore", but the test does not simulate a no longer matching query.
Additionally adding `await nextTick();` before emitting the `updated` event breaks the test. That should not happen.

**Comment by lukashass** [comment]
@anbraten Am I missing something?

**Comment by anbraten** [comment]
@lukashass I think the query stays the same, but the object which was first matched changed and is not matching the query anymore after that update / patch. 

Exp: 
query: `{ type: "dog" }`
data: `{ _id: "123", type: "dog", name: "Pluto" }`
=> we have one item in matching data
update:  `{ _id: "123", type: "dog", name: "Pluto" }` =>  `{ _id: "123", type: "cat", name: "Pluto" }`
=> we have 0 items in matching data
